"""Optical-force and moving-interference analysis for the Bessel-beam pair.

Reference
---------
M. M. Rahman et al., "Tractor beam for fully immersed multiple objects:
Long distance pulling, trapping, and rotation with a single optical set-up,"
Annalen der Physik 527, 777-793 (2015), DOI: 10.1002/andp.201500266.

This module implements the paper's Eqs. (2)-(4) and the interference-pattern
rates discussed after Eq. (5b). It uses the electric-field arrays generated by
``BesselBeamGasLiquidForceFunc.py`` and applies the paper's dipole model.
"""

from __future__ import annotations

import numpy as np


EPS0 = 8.854187817e-12
C0 = 299_792_458.0


def electric_intensity(field_squared, medium_index, *, c=C0):
    """Return time-averaged intensity in W/m^2.

    Parameters
    ----------
    field_squared : array_like
        ``|E_rho|^2 + |E_phi|^2 + |E_z|^2`` in (V/m)^2.
    medium_index : float
        Refractive index of the surrounding liquid, ``eta_m`` in the paper.

    Notes
    -----
    Implements ``I = eta_m * eps0 * c * |E|^2 / 2`` from Eq. (2).
    """
    return 0.5 * medium_index * EPS0 * c * np.asarray(field_squared)


def dipole_force_coefficient(particle_index, medium_index, particle_radius,
                             wavelength_vacuum, *, c=C0):
    """Return the coefficient ``X`` from Eq. (2), including its correction.

    The dipole model is intended for ``k*r_p <= 1``, approximately
    ``r_p <= wavelength/(2*pi)``.  A ValueError is raised outside that range.
    """
    rp = float(particle_radius)
    wavelength = float(wavelength_vacuum)
    size_parameter = 2.0 * np.pi * rp / wavelength
    if size_parameter > 1.0:
        raise ValueError(
            "Dipole approximation violated: 2*pi*r_p/lambda must be <= 1 "
            f"(received {size_parameter:.4g})."
        )
    contrast = (particle_index**2 - medium_index**2) / (
        particle_index**2 + 2.0 * medium_index**2
    )
    correction = 1.0 / (1.0 + ((2.0 / 3.0) * contrast * size_parameter**3) ** 2)
    return (medium_index / c) * 1.5 * contrast * correction


def gradient_force_and_potential(intensity, x, y, z, particle_index,
                                 medium_index, particle_radius,
                                 wavelength_vacuum):
    """Compute Cartesian gradient force and optical potential.

    ``intensity`` must have shape ``(len(z), len(y), len(x))``.  The returned
    ``Fx, Fy, Fz`` are in newtons and ``potential`` is in joules.

    The paper gives ``F_grad = X*V*grad(I)`` and ``P = -X*V*I`` in cylindrical
    coordinates (Eqs. 3-4). A Cartesian gradient is equivalent and avoids the
    numerical singularity of ``(1/rho)*dI/dphi`` at the beam axis.
    """
    intensity = np.asarray(intensity, dtype=float)
    x, y, z = map(lambda a: np.asarray(a, dtype=float), (x, y, z))
    expected = (z.size, y.size, x.size)
    if intensity.shape != expected:
        raise ValueError(f"intensity shape must be {expected}, got {intensity.shape}")
    Xcoef = dipole_force_coefficient(
        particle_index, medium_index, particle_radius, wavelength_vacuum
    )
    volume = (4.0 / 3.0) * np.pi * particle_radius**3
    dI_dz, dI_dy, dI_dx = np.gradient(intensity, z, y, x, edge_order=2)
    scale = Xcoef * volume
    return {
        "Fx": scale * dI_dx, "Fy": scale * dI_dy, "Fz": scale * dI_dz,
        "potential": -scale * intensity, "X": Xcoef, "volume": volume,
        "light_seeking": bool(particle_index > medium_index),
    }


def pattern_velocities(omega, beta_liquid, orders):
    """Return the paper's axial and azimuthal interference-pattern rates.

    ``v_z = (omega1-omega2)/(beta1-beta2)`` [m/s]
    ``Omega_phi = (omega1-omega2)/(m1-m2)`` [rad/s]

    A positive or negative sign gives the direction under the phase convention
    ``exp(i*(beta*z + m*phi - omega*t))`` used by the translated code.
    """
    omega = np.asarray(omega, dtype=float)
    beta = np.asarray(beta_liquid, dtype=float)
    m = np.asarray(orders, dtype=float)
    if omega.size != 2 or beta.size != 2 or m.size != 2:
        raise ValueError("omega, beta_liquid, and orders must each contain two values")
    domega, dbeta, dm = omega[0] - omega[1], beta[0] - beta[1], m[0] - m[1]
    vz = np.inf if dbeta == 0 else domega / dbeta
    angular_rate = np.inf if dm == 0 else domega / dm
    return {
        "delta_omega": domega, "delta_beta": dbeta, "delta_m": dm,
        "axial_speed_m_per_s": vz,
        "angular_rate_rad_per_s": angular_rate,
        "rotation_rate_rev_per_s": angular_rate / (2.0 * np.pi),
        "azimuthal_lobes_for_reverse_orders": int(abs(dm)),
    }
